
import { Car, Categoria, Marca, Testimonio } from "./types";

export const MARCAS = [
  "Audi",
  "BMW",
  "Citroën",
  "Dacia",
  "Fiat",
  "Ford",
  "Honda",
  "Hyundai",
  "Kia",
  "Mazda",
  "Mercedes",
  "Nissan",
  "Opel",
  "Peugeot",
  "Renault",
  "SEAT",
  "Skoda",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const ANOS = Array.from({ length: 2025 - 1990 + 1 }, (_, i) => 2025 - i);

export const PROVINCIAS = [
  "A Coruña",
  "Álava",
  "Albacete",
  "Alicante",
  "Almería",
  "Asturias",
  "Ávila",
  "Badajoz",
  "Barcelona",
  "Burgos",
  "Cáceres",
  "Cádiz",
  "Cantabria",
  "Castellón",
  "Ciudad Real",
  "Córdoba",
  "Cuenca",
  "Girona",
  "Granada",
  "Guadalajara",
  "Guipúzcoa",
  "Huelva",
  "Huesca",
  "Islas Baleares",
  "Jaén",
  "La Rioja",
  "Las Palmas",
  "León",
  "Lleida",
  "Lugo",
  "Madrid",
  "Málaga",
  "Murcia",
  "Navarra",
  "Ourense",
  "Palencia",
  "Pontevedra",
  "Salamanca",
  "Santa Cruz de Tenerife",
  "Segovia",
  "Sevilla",
  "Soria",
  "Tarragona",
  "Teruel",
  "Toledo",
  "Valencia",
  "Valladolid",
  "Vizcaya",
  "Zamora",
  "Zaragoza",
];

export const FEATURED_CARS: Car[] = [
  {
    id: "1",
    marca: "BMW",
    modelo: "Serie 3",
    version: "320d",
    ano: 2021,
    precio: 38500,
    kilometros: 25000,
    combustible: "Diésel",
    cambio: "Automático",
    potencia: 190,
    provincia: "Madrid",
    descripcionCorta: "Excelente estado, único dueño",
    descripcion: "BMW Serie 3 320d con acabado M Sport. Vehículo en perfectas condiciones, revisiones al día en servicio oficial BMW. Equipamiento completo con navegador, faros LED, asientos deportivos, etc.",
    imagenPrincipal: "https://images.unsplash.com/photo-1555215695-3004980ad54e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8Ym13JTIwMzIwZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60",
    imagenes: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8Ym13JTIwMzIwZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Ym13JTIwMzIwZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60",
    ],
    caracteristicas: [
      "Navegador",
      "Faros LED",
      "Asientos deportivos",
      "Llantas 19\"",
      "Climatizador bizona",
      "Sensores de aparcamiento",
      "Cámara trasera",
    ],
    vendedor: {
      id: "v1",
      nombre: "AutoPremium",
      tipo: "profesional",
      telefono: "911234567",
      valoracion: 4.8,
    },
    esDestacado: true,
    fechaPublicacion: "2023-09-15",
  },
  {
    id: "2",
    marca: "Mercedes",
    modelo: "Clase C",
    version: "C220d",
    ano: 2022,
    precio: 42900,
    kilometros: 18000,
    combustible: "Diésel",
    cambio: "Automático",
    potencia: 200,
    provincia: "Barcelona",
    descripcionCorta: "Como nuevo, garantía oficial",
    descripcion: "Mercedes Clase C C220d con acabado AMG Line. Vehículo prácticamente nuevo con garantía oficial hasta 2025. Full equipo incluyendo techo panorámico, head-up display, paquete MBUX, etc.",
    imagenPrincipal: "https://images.unsplash.com/photo-1617469867041-138c86d6d1e1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8bWVyY2VkZXMlMjBjbGFzcyUyMGN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
    imagenes: [
      "https://images.unsplash.com/photo-1617469867041-138c86d6d1e1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8bWVyY2VkZXMlMjBjbGFzcyUyMGN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8bWVyY2VkZXMlMjBjbGFzcyUyMGN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
    ],
    caracteristicas: [
      "Techo panorámico",
      "Head-up Display",
      "Paquete MBUX",
      "Asientos calefactables",
      "Sistema de sonido Burmester",
      "Suspensión adaptativa",
      "Paquete asistencia a la conducción",
    ],
    vendedor: {
      id: "v2",
      nombre: "AutoLuxury",
      tipo: "profesional",
      telefono: "932345678",
      valoracion: 4.9,
    },
    esDestacado: true,
    fechaPublicacion: "2023-10-02",
  },
  {
    id: "3",
    marca: "Audi",
    modelo: "A3",
    version: "Sportback 35 TDI",
    ano: 2023,
    precio: 36700,
    kilometros: 5000,
    combustible: "Diésel",
    cambio: "Automático",
    potencia: 150,
    provincia: "Valencia",
    descripcionCorta: "Seminuevo, todos los extras",
    descripcion: "Audi A3 Sportback 35 TDI S-Line. Vehículo seminuevo con muy pocos kilómetros. Equipado con paquete S-Line exterior e interior, tecnología Audi Connect, sistema de navegación MMI plus, etc.",
    imagenPrincipal: "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YXVkaSUyMGEzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
    imagenes: [
      "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YXVkaSUyMGEzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1612911912304-5c58cc8c4f4f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YXVkaSUyMGEzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
    ],
    caracteristicas: [
      "Paquete S-Line",
      "Audi Connect",
      "MMI Navigation plus",
      "Virtual Cockpit",
      "Llantas de 18\"",
      "Faros Matrix LED",
      "Sistema de sonido Bang & Olufsen",
    ],
    vendedor: {
      id: "v3",
      nombre: "CarMotors",
      tipo: "profesional",
      telefono: "963456789",
      valoracion: 4.7,
    },
    esDestacado: true,
    fechaPublicacion: "2023-10-15",
  },
  {
    id: "4",
    marca: "Volkswagen",
    modelo: "Golf",
    version: "1.5 TSI",
    ano: 2022,
    precio: 32500,
    kilometros: 15000,
    combustible: "Gasolina",
    cambio: "Manual",
    potencia: 130,
    provincia: "Sevilla",
    descripcionCorta: "Impecable, kilometraje certificado",
    descripcion: "Volkswagen Golf 1.5 TSI Style. Vehículo en perfecto estado con libro de mantenimiento al día. Equipamiento completo incluyendo Digital Cockpit Pro, faros IQ.Light LED matrix, sistema de navegación Discover Pro, etc.",
    imagenPrincipal: "https://images.unsplash.com/photo-1621019519107-ca0d7e3d169a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dm9sa3N3YWdlbiUyMGdvbGYlMjA4fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
    imagenes: [
      "https://images.unsplash.com/photo-1621019519107-ca0d7e3d169a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dm9sa3N3YWdlbiUyMGdvbGYlMjA4fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1622807039708-00b33d204e2b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dm9sa3N3YWdlbiUyMGdvbGYlMjA4fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
    ],
    caracteristicas: [
      "Digital Cockpit Pro",
      "IQ.Light LED matrix",
      "Discover Pro",
      "App-Connect",
      "Climatizador tritzona",
      "Sensor de aparcamiento",
      "Cargador inalámbrico",
    ],
    vendedor: {
      id: "v4",
      nombre: "Juan García",
      tipo: "particular",
      telefono: "654321987",
      valoracion: 4.9,
    },
    esDestacado: false,
    fechaPublicacion: "2023-09-28",
  },
];

export const CATEGORIAS: Categoria[] = [
  {
    id: "c1",
    nombre: "SUV / Todoterreno",
    slug: "suv-todoterreno",
    icono: "https://cdn-icons-png.flaticon.com/512/741/741407.png",
    cantidad: 4586,
  },
  {
    id: "c2",
    nombre: "Berlinas",
    slug: "berlinas",
    icono: "https://cdn-icons-png.flaticon.com/512/741/741470.png",
    cantidad: 3255,
  },
  {
    id: "c3",
    nombre: "Compactos",
    slug: "compactos",
    icono: "https://cdn-icons-png.flaticon.com/512/741/741380.png",
    cantidad: 2899,
  },
  {
    id: "c4",
    nombre: "Familiares",
    slug: "familiares",
    icono: "https://cdn-icons-png.flaticon.com/512/741/741390.png",
    cantidad: 1876,
  },
  {
    id: "c5",
    nombre: "Deportivos",
    slug: "deportivos",
    icono: "https://cdn-icons-png.flaticon.com/512/741/741415.png",
    cantidad: 765,
  },
  {
    id: "c6",
    nombre: "Eléctricos",
    slug: "electricos",
    icono: "https://cdn-icons-png.flaticon.com/512/1933/1933078.png",
    cantidad: 1243,
  },
];

export const MARCAS_POPULARES: Marca[] = [
  {
    id: "m1",
    nombre: "Audi",
    slug: "audi",
    logo: "https://cdn.icon-icons.com/icons2/2402/PNG/512/audi_logo_icon_145840.png",
  },
  {
    id: "m2",
    nombre: "BMW",
    slug: "bmw",
    logo: "https://cdn.icon-icons.com/icons2/2402/PNG/512/bmw_logo_icon_145861.png",
  },
  {
    id: "m3",
    nombre: "Mercedes",
    slug: "mercedes",
    logo: "https://cdn.icon-icons.com/icons2/2402/PNG/512/mercedes_benz_logo_icon_145798.png",
  },
  {
    id: "m4",
    nombre: "Volkswagen",
    slug: "volkswagen",
    logo: "https://cdn.icon-icons.com/icons2/2402/PNG/512/volkswagen_logo_icon_145773.png",
  },
  {
    id: "m5",
    nombre: "Toyota",
    slug: "toyota",
    logo: "https://cdn.icon-icons.com/icons2/2402/PNG/512/toyota_logo_icon_145768.png",
  },
  {
    id: "m6",
    nombre: "SEAT",
    slug: "seat",
    logo: "https://cdn.icon-icons.com/icons2/2402/PNG/512/seat_logo_icon_145791.png",
  },
];

export const TESTIMONIOS: Testimonio[] = [
  {
    id: "t1",
    nombre: "Carlos Rodríguez",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    comentario: "Encontré mi BMW Serie 3 en menos de una semana. El proceso fue muy fácil y pude negociar directamente con el vendedor sin comisiones.",
    estrellas: 5,
    vehiculo: "BMW Serie 3",
  },
  {
    id: "t2",
    nombre: "Laura Martínez",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    comentario: "Como particular, pude vender mi coche en solo 3 días gracias a la visibilidad que me dio la plataforma. Muy recomendable.",
    estrellas: 4,
    vehiculo: "Seat León",
  },
  {
    id: "t3",
    nombre: "Miguel Fernández",
    avatar: "https://randomuser.me/api/portraits/men/67.jpg",
    comentario: "La búsqueda avanzada me permitió encontrar exactamente el modelo que buscaba con todas las características que necesitaba.",
    estrellas: 5,
    vehiculo: "Audi Q3",
  },
];
